name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
    #schedule:
    #    - cron: '42 5 * * 0'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          # The module itself requires perl 5.14
          #- '5.14'
          - '5.16' # JSON is missing
          - '5.18' # JSON is missing
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.38'
          - '5.40'
          - '5.42'
#          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v6

      - name: Show Perl version
        run: perl -v

      - name: Prepare for release tests
        run: |
            cpanm --installdeps --notest --verbose .
            cpanm --notest --verbose Test::CheckManifest
            cpanm --notest --verbose JSON # Needed by 5.16 and 5.18
      - name: Release tests
        #env:
        #  RELEASE_TESTING: 1
        run: |
            perl Makefile.PL
            make
            PERL5LIB=$PERL5LIB:$(pwd)/lib:$(pwd)/t/lib make test

